name: Issue Report
description: Create a issue  to help us improve
title: "[Issue] : "
labels: "issue"
body :
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our issue report form 🙏
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "Issue Description"
      description: "Please walk us through issue step by step. Upload the image if necessary for demo."
    validations:
      required: true
  - type: checkboxes
    id: hacktober-fest-contributor
    attributes:
      label: "Are you a Hacktoberfest'21 contributor"
      description: "Let us know weather you are a Hacktoberfest'21 contributor"
      options:
        - label: "Yes, I'am Hacktoberfest'21 contributor"
          required: true
